# Generated by Django 4.1 on 2022-08-23 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_first_name", models.CharField(max_length=15)),
                ("customer_middle_name", models.CharField(max_length=15)),
                ("customer_last_name", models.CharField(max_length=15)),
                ("customer_email_id", models.CharField(max_length=35)),
                ("customer_dob", models.DateField(max_length=10)),
                ("customer_phone_number", models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name="Product_Type",
            fields=[
                (
                    "product_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("product_type_name", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=15)),
                ("product_description", models.CharField(max_length=100)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_quantity", models.PositiveIntegerField()),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_shop_api.product_type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sell",
            fields=[
                (
                    "transaction_sell_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("sell_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("sell_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sell_quantity", models.PositiveIntegerField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_shop_api.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "transaction_purchase_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "purchase_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("purchase_quantity", models.PositiveIntegerField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_shop_api.products",
                    ),
                ),
            ],
        ),
    ]
